# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Values.nest_next_client.name }}-service
# spec:
#   type: {{ .Values.nest_next_client.service.type }}
#   ports:
#     - port: 3000
#       targetPort: {{ .Values.nest_next_client.image.exposedPort }}
#   selector:
#     server: {{ .Values.nest_next_client.name }}
apiVersion: v1
kind: Service
metadata:
  name: nest-next-client-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    server: nest-next-client
