apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nest_next_client.name }}-service
spec:
  type: {{ .Values.nest_next_client.service.type }}
  ports:
    - port: 80 # 3000
      targetPort: {{ .Values.nest_next_client.image.exposedPort }}
  selector:
    server: {{ .Values.nest_next_client.name }}
