apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nest_next_client.name }}-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      server: {{ .Values.nest_next_client.name }}
  template:
    metadata:
      labels:
        server: {{ .Values.nest_next_client.name }}
    spec:
      containers:
        - name: {{ .Values.nest_next_client.name }}
          image: {{ .Values.nest_next_client.name }}:{{ .Values.nest_next_client.image.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.nest_next_client.image.exposedPort }}
          env:
            - name: NODE_ENV
              value: {{ .Values.nest_next_client.env.NODE_ENV }}
