apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nest_next_server.name }}-service
spec:
  type: {{ .Values.nest_next_server.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.nest_next_server.image.exposedPort }}
  selector:
    server: {{ .Values.nest_next_server.name }}
